#!/usr/bin/env python3
"""Generate assets/data.js from the official Montclair Porchfest CSV.

Reads montclair_porchfest_2026.csv (Address, Band Name, Time), geocodes each
unique address via Nominatim, and writes a data.js compatible with app.js.
"""
import csv, json, re, sys, time, urllib.parse, urllib.request, pathlib

CSV_PATH = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path("montclair_porchfest_2026.csv")
OUT_PATH = pathlib.Path(__file__).resolve().parent.parent / "assets" / "data.js"
CACHE_PATH = pathlib.Path(__file__).resolve().parent / "geocode_cache.json"

NOMINATIM = "https://nominatim.openstreetmap.org/search"
UA = "porchfest-map/1.0 (matt@mu.design)"

def normalize_addr(raw: str) -> str:
    a = raw.strip()
    # fix typos & abbreviations
    a = re.sub(r"\bStret\b", "Street", a)
    a = re.sub(r"\bCentralAve\b", "Central Ave", a)
    a = re.sub(r"\bGove Street\b", "Grove Street", a)  # "410 Gove Street" → Grove
    a = re.sub(r"\bN\s+Mountain Ave\b", "North Mountain Ave", a)
    a = re.sub(r"\bS\s+Fullerton Ave\b", "South Fullerton Ave", a)
    a = re.sub(r"\bN\s+Fullerton Ave\b", "North Fullerton Ave", a)
    a = re.sub(r"\bN\s+Willow Street\b", "North Willow Street", a)
    a = re.sub(r"\b2 Edgemont Ave\b", "2 Edgemont Road", a)  # not on Edgemont Ave
    return a

def derive_area(address: str) -> str:
    """Pull the street name out of an address, e.g. '34 Walnut St' -> 'Walnut St'."""
    m = re.match(r"^\d+\s+(.+)$", address.strip())
    return m.group(1) if m else address

def geocode(address: str, cache: dict):
    key = address
    if key in cache:
        return cache[key]
    q = f"{address}, Montclair, NJ"
    url = f"{NOMINATIM}?{urllib.parse.urlencode({'q': q, 'format': 'json', 'limit': 1})}"
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=15) as resp:
        data = json.load(resp)
    if data:
        result = {"lat": float(data[0]["lat"]), "lng": float(data[0]["lon"])}
    else:
        result = None
    cache[key] = result
    CACHE_PATH.write_text(json.dumps(cache, indent=2))
    time.sleep(1.1)  # Nominatim rate limit
    return result

def parse_time(t: str) -> int:
    """'11:00 AM' -> minutes since midnight."""
    m = re.match(r"(\d+):(\d+)\s*([AP]M)", t.strip())
    h, mi, ap = int(m.group(1)), int(m.group(2)), m.group(3)
    if ap == "PM" and h != 12: h += 12
    if ap == "AM" and h == 12: h = 0
    return h * 60 + mi

def porch_id(idx: int) -> str:
    return f"p{idx:03d}"

def main():
    cache = json.loads(CACHE_PATH.read_text()) if CACHE_PATH.exists() else {}

    with CSV_PATH.open() as f:
        rows = list(csv.DictReader(f))

    # unique addresses preserving order
    seen, porches = {}, []
    for r in rows:
        addr = normalize_addr(r["Address"])
        if addr not in seen:
            seen[addr] = porch_id(len(porches) + 1)
            porches.append({"id": seen[addr], "address": addr, "area": derive_area(addr)})

    # geocode
    for p in porches:
        loc = geocode(p["address"], cache)
        if loc:
            p["lat"], p["lng"] = loc["lat"], loc["lng"]
        else:
            print(f"WARN no geocode for {p['address']!r}", file=sys.stderr)
            p["lat"], p["lng"] = None, None

    # acts
    acts = []
    for i, r in enumerate(rows, 1):
        addr = normalize_addr(r["Address"])
        start = parse_time(r["Time"])
        acts.append({
            "id": f"a{i:03d}",
            "artist": r["Band Name"].strip(),
            "genre": "",
            "porchId": seen[addr],
            "start": start,
            "end": start + 45,
        })

    # festival bounds from data
    starts = [a["start"] for a in acts]
    ends = [a["end"] for a in acts]
    fest_start = min(starts)
    fest_end = max(ends)

    # compute center from porches with coords
    coords = [(p["lat"], p["lng"]) for p in porches if p["lat"] is not None]
    if coords:
        center = {"lat": sum(c[0] for c in coords) / len(coords),
                  "lng": sum(c[1] for c in coords) / len(coords)}
    else:
        center = {"lat": 40.8259, "lng": -74.2090}

    festival = {
        "name": "Montclair Porchfest",
        "date": "2026-05-16",
        "dateLabel": "Saturday, May 16, 2026",
        "startMinutes": fest_start,
        "endMinutes": fest_end,
        "center": center,
    }

    out = [
        "// Auto-generated by scripts/build_data.py from montclair_porchfest_2026.csv.",
        "// Do not edit by hand — re-run the script to refresh.",
        "",
        f"const FESTIVAL = {json.dumps(festival, indent=2)};",
        "",
        f"const PORCHES = {json.dumps(porches, indent=2)};",
        "",
        f"const ACTS = {json.dumps(acts, indent=2)};",
        "",
        "const PORCH_BY_ID = Object.fromEntries(PORCHES.map(p => [p.id, p]));",
        "",
        "const SCHEDULE = ACTS.map(a => ({ ...a, porch: PORCH_BY_ID[a.porchId] }))",
        "  .sort((a, b) => a.start - b.start || a.artist.localeCompare(b.artist));",
        "",
        "window.PorchfestData = { FESTIVAL, PORCHES, ACTS, PORCH_BY_ID, SCHEDULE };",
        "",
    ]
    OUT_PATH.write_text("\n".join(out))
    print(f"wrote {OUT_PATH} — {len(porches)} porches, {len(acts)} acts")

if __name__ == "__main__":
    main()
